title: Omkar Nitturkar   
logo: https://github.com/omkarnitturkar/omkarnitturkar/blob/main/BATMAN_GRADE_AT_001_BATMOBILE_001_001_2022-03-02_15.49.32.jpg
description: Data Analyst 
# show_downloads: true
theme: jekyll-theme-Cayman
